# Generated by Django 5.2.6 on 2025-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.CharField(default='test@example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
