# Generated by Django 5.2.6 on 2025-09-13 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_manager', '0003_alter_vaultitem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultitem',
            name='user',
            field=models.ForeignKey(default=7622020906, on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
